[tool.cibuildwheel]
build-verbosity = "3"
[build-system]
requires = [
    "numpy<=1.96.0",
    "scipy",
    "setuptools>=42",
    "wheel",
    "cmake>=3.16",
    "packaging"
]

build-backend = "setuptools.build_meta"